version: '3.8'

volumes:
  postgres_volume:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 8000:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
